/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;

import javacrud.tech.GestionSMTP;

/**
 *
 * @author l.milan
 */
public class Mail extends javax.swing.JFrame {

    /**
     * Creates new form Mail
     */
    private GestionSMTP gestionMail;

    public Mail(String destinataire) {
        initComponents();
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255, 100));
        TextField_Destinataire.setText(destinataire);
        this.gestionMail = new GestionSMTP();
    }
    
    public Mail() {
        initComponents();
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255, 100));
        this.gestionMail = new GestionSMTP();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Mail = new javax.swing.JTextArea();
        TextField_Destinataire = new javax.swing.JTextField();
        TextField_Objet = new javax.swing.JTextField();
        Label_Destinaire = new javax.swing.JLabel();
        Label_Objet = new javax.swing.JLabel();
        Label_Mail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Button_Envoyer = new javax.swing.JButton();
        bouton_Retour = new javax.swing.JButton();
        jButton_UtilCrud = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(128, 255, 30));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextArea_Mail.setColumns(20);
        TextArea_Mail.setRows(5);
        jScrollPane1.setViewportView(TextArea_Mail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 213, 739, 237));

        TextField_Destinataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DestinataireActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Destinataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 111, 739, 36));

        TextField_Objet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ObjetActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Objet, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 159, 739, 36));

        Label_Destinaire.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Destinaire.setForeground(new java.awt.Color(255, 255, 255));
        Label_Destinaire.setText("Destinataire :");
        getContentPane().add(Label_Destinaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 36));

        Label_Objet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Objet.setForeground(new java.awt.Color(255, 255, 255));
        Label_Objet.setText("Objet :");
        getContentPane().add(Label_Objet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));

        Label_Mail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Mail.setForeground(new java.awt.Color(255, 255, 255));
        Label_Mail.setText("Mail :");
        getContentPane().add(Label_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, 60, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Envoyer un mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 34, 360, 36));

        Button_Envoyer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Envoyer.setText("Envoyer");
        Button_Envoyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_EnvoyerMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Envoyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 481, -1, -1));

        bouton_Retour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bouton_Retour.setText("Retour");
        bouton_Retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_RetourMouseClicked(evt);
            }
        });
        getContentPane().add(bouton_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 481, -1, -1));

        jButton_UtilCrud.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_UtilCrud.setText("UtilCrud");
        jButton_UtilCrud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_UtilCrudMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_UtilCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0,128,255,30));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/technology-background-1632715.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_DestinataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DestinataireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DestinataireActionPerformed

    private void TextField_ObjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ObjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ObjetActionPerformed

    private void bouton_RetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_RetourMouseClicked
        // TODO add your handling code here:
        //gestionMail.closeSMTPCon();
        //gestionMail = null;
        this.dispose();
        Mainform mainform = new Mainform();
        mainform.setVisible(true);
    }//GEN-LAST:event_bouton_RetourMouseClicked

    private void Button_EnvoyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_EnvoyerMouseClicked
        // TODO add your handling code here:
        gestionMail.setMailTo(TextField_Destinataire.getText().strip());
        gestionMail.setMailObj(TextField_Objet.getText().strip());
        gestionMail.setMailMsg(TextArea_Mail.getText());// *UTF-8");
        try {
            gestionMail.sendMsg();
        } catch (Exception ev) {
            ev.printStackTrace();
        }
    }//GEN-LAST:event_Button_EnvoyerMouseClicked

    private void jButton_UtilCrudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UtilCrudMouseClicked
        // TODO add your handling code here:
        UtilCrud jfUtilCrud = new UtilCrud();
        jfUtilCrud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_UtilCrudMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Envoyer;
    private javax.swing.JLabel Label_Destinaire;
    private javax.swing.JLabel Label_Mail;
    private javax.swing.JLabel Label_Objet;
    private javax.swing.JTextArea TextArea_Mail;
    private javax.swing.JTextField TextField_Destinataire;
    private javax.swing.JTextField TextField_Objet;
    private javax.swing.JButton bouton_Retour;
    private javax.swing.JButton jButton_UtilCrud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
