/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;
import javacrud.control.ImageDAO;
import javax.swing.ImageIcon;

/**
 *
 * @author l.milan
 */
public class SelectAvatar extends javax.swing.JFrame {

    /**
     * Creates new form SelectAvatar
     */
    public SelectAvatar(java.awt.Frame parent, boolean modal) {
        initComponents();
    }
    
    public SelectAvatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Quitter = new javax.swing.JButton();
        jButton_Choisir = new javax.swing.JButton();
        jLabel_AvatarGrand = new javax.swing.JLabel();
        jLabel_AvatarPetit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Quitter.setIcon(new javax.swing.ImageIcon("C:\\Users\\l.milan\\Documents\\MILAN Lilian\\2ème année\\JavaCRUD\\JavaCRUD\\src\\ressource\\escape_20.png")); // NOI18N
        jButton_Quitter.setText("Quitter");
        jButton_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_QuitterMousePressed(evt);
            }
        });

        jButton_Choisir.setIcon(new javax.swing.ImageIcon("C:\\Users\\l.milan\\Documents\\MILAN Lilian\\2ème année\\JavaCRUD\\JavaCRUD\\src\\ressource\\folder-open_20.png")); // NOI18N
        jButton_Choisir.setText("Choisir");

        jLabel_AvatarGrand.setIcon(new javax.swing.ImageIcon("C:\\Users\\l.milan\\Documents\\MILAN Lilian\\2ème année\\JavaCRUD\\JavaCRUD\\src\\ressource\\user-tie-max.jpg")); // NOI18N

        jLabel_AvatarPetit.setIcon(new javax.swing.ImageIcon("C:\\Users\\l.milan\\Documents\\MILAN Lilian\\2ème année\\JavaCRUD\\JavaCRUD\\src\\ressource\\user-tie-min.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Choisir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_AvatarGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel_AvatarPetit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_AvatarGrand, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_AvatarPetit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Quitter)
                    .addComponent(jButton_Choisir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_QuitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_QuitterMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_QuitterMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectAvatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Choisir;
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JLabel jLabel_AvatarGrand;
    private javax.swing.JLabel jLabel_AvatarPetit;
    // End of variables declaration//GEN-END:variables
}
