/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacrud.view;

import java.awt.Frame;
import java.sql.Connection;
import javacrud.view.UtilCrud;
import java.sql.Statement;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javacrud.model.Utilisateur;
import javacrud.control.UtilisateurDAOImp;
import javacrud.model.Commune;

/**
 *
 * @author l.milan
 */
public class UtilCrud extends javax.swing.JFrame {

    /**
     * Creates new form UtilCrud
     */
    Connection con;
    Statement st;
    //LinkedList<Utilisateur> lesUtilisateurs = new LinkedList<>();
    TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    UtilisateurDAOImp dao = new UtilisateurDAOImp();
    Commune commune = new Commune();
    String uiNumpost;
    private Frame UtilCrud;
    private Object[] selectedVille;

    public UtilCrud() {
        initComponents();
        jLabel8_Message.setText("Veuillez choisir un utilisateur dans le tableau de gauche ou saisir les données à créer");
        chargerLesUtilisateurs();
        jLabel13_CP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2_Nom = new javax.swing.JLabel();
        jLabel3_Prenom = new javax.swing.JLabel();
        jTextField2_Nom = new javax.swing.JTextField();
        jTextField1_Prenom = new javax.swing.JTextField();
        jLabel4_Utilisateur = new javax.swing.JLabel();
        jTextField3_Utilisateur = new javax.swing.JTextField();
        jLabel5_Mail = new javax.swing.JLabel();
        jTextField4_Mail = new javax.swing.JTextField();
        jLabel6_MotDePasse = new javax.swing.JLabel();
        jTextField5_MotDePassse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1_Creer = new javax.swing.JButton();
        jButton2_Modifier = new javax.swing.JButton();
        jButton3_Supprimer = new javax.swing.JButton();
        jButton4_Nouveau = new javax.swing.JButton();
        jTextField6_Adresse = new javax.swing.JTextField();
        jTextField7_Adresse2 = new javax.swing.JTextField();
        jTextField8_CodePostal = new javax.swing.JTextField();
        jTextField9_Ville = new javax.swing.JTextField();
        jButton5_Parametre = new javax.swing.JButton();
        jButton6_Mail = new javax.swing.JButton();
        jButton7_AuSujet = new javax.swing.JButton();
        jButton8_Aide = new javax.swing.JButton();
        jButton9_Quitter = new javax.swing.JButton();
        jButton10_Ville = new javax.swing.JButton();
        jButton11_Photo = new javax.swing.JButton();
        jLabel14_Avatar = new javax.swing.JLabel();
        jLabel13_CP = new javax.swing.JLabel();
        jLabel7_CodePostal = new javax.swing.JLabel();
        jLabel6_Adresse = new javax.swing.JLabel();
        jLabel8_Message = new javax.swing.JLabel();
        jLabel3_Phrase = new javax.swing.JLabel();
        jLabel2_LittleBackground = new javax.swing.JLabel();
        jLabel9_Background = new javax.swing.JLabel();
        jLabel11_Background = new javax.swing.JLabel();
        jLabel12_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(965, 605));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CRUD SIMPLIFIE : GESTION DES UTILISATEURS ET AUTRES RESSOURCES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(65, 0, 479, 63);

        jLabel2_Nom.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Nom.setText("Nom");
        getContentPane().add(jLabel2_Nom);
        jLabel2_Nom.setBounds(440, 110, 27, 16);

        jLabel3_Prenom.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_Prenom.setText("Prénom");
        getContentPane().add(jLabel3_Prenom);
        jLabel3_Prenom.setBounds(440, 150, 42, 20);

        jTextField2_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2_Nom);
        jTextField2_Nom.setBounds(520, 110, 210, 30);
        getContentPane().add(jTextField1_Prenom);
        jTextField1_Prenom.setBounds(520, 150, 210, 30);

        jLabel4_Utilisateur.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_Utilisateur.setText("Utilisateur");
        getContentPane().add(jLabel4_Utilisateur);
        jLabel4_Utilisateur.setBounds(440, 190, 60, 16);

        jTextField3_Utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_UtilisateurActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3_Utilisateur);
        jTextField3_Utilisateur.setBounds(520, 190, 210, 30);

        jLabel5_Mail.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_Mail.setText("Mail");
        getContentPane().add(jLabel5_Mail);
        jLabel5_Mail.setBounds(440, 230, 37, 16);
        getContentPane().add(jTextField4_Mail);
        jTextField4_Mail.setBounds(520, 230, 290, 30);

        jLabel6_MotDePasse.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_MotDePasse.setText("Mot de passe");
        getContentPane().add(jLabel6_MotDePasse);
        jLabel6_MotDePasse.setBounds(440, 270, 80, 16);
        getContentPane().add(jTextField5_MotDePassse);
        jTextField5_MotDePassse.setBounds(520, 270, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Utilisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 400, 460);

        jButton1_Creer.setText("Creer");
        jButton1_Creer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_CreerMouseClicked(evt);
            }
        });
        jButton1_Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CreerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Creer);
        jButton1_Creer.setBounds(440, 480, 72, 22);

        jButton2_Modifier.setText("Modifier");
        jButton2_Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_ModifierMouseClicked(evt);
            }
        });
        getContentPane().add(jButton2_Modifier);
        jButton2_Modifier.setBounds(530, 480, 75, 22);

        jButton3_Supprimer.setText("Supprimer");
        jButton3_Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_SupprimerMouseClicked(evt);
            }
        });
        getContentPane().add(jButton3_Supprimer);
        jButton3_Supprimer.setBounds(640, 480, 110, 22);

        jButton4_Nouveau.setText("Nouveau");
        jButton4_Nouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_NouveauMouseClicked(evt);
            }
        });
        getContentPane().add(jButton4_Nouveau);
        jButton4_Nouveau.setBounds(820, 480, 110, 22);
        getContentPane().add(jTextField6_Adresse);
        jTextField6_Adresse.setBounds(520, 310, 290, 30);
        getContentPane().add(jTextField7_Adresse2);
        jTextField7_Adresse2.setBounds(520, 350, 290, 30);
        getContentPane().add(jTextField8_CodePostal);
        jTextField8_CodePostal.setBounds(520, 390, 120, 30);
        getContentPane().add(jTextField9_Ville);
        jTextField9_Ville.setBounds(520, 430, 290, 30);

        jButton5_Parametre.setText("Paramètre");
        getContentPane().add(jButton5_Parametre);
        jButton5_Parametre.setBounds(20, 530, 110, 22);

        jButton6_Mail.setText("Mail");
        jButton6_Mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6_MailMouseClicked(evt);
            }
        });
        getContentPane().add(jButton6_Mail);
        jButton6_Mail.setBounds(550, 530, 80, 30);

        jButton7_AuSujet.setText("Au sujet");
        getContentPane().add(jButton7_AuSujet);
        jButton7_AuSujet.setBounds(640, 530, 100, 30);

        jButton8_Aide.setText("Aide");
        getContentPane().add(jButton8_Aide);
        jButton8_Aide.setBounds(750, 530, 80, 30);

        jButton9_Quitter.setText("Retour");
        jButton9_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9_QuitterMouseClicked(evt);
            }
        });
        getContentPane().add(jButton9_Quitter);
        jButton9_Quitter.setBounds(840, 530, 100, 30);

        jButton10_Ville.setText("Ville");
        jButton10_Ville.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10_VilleMouseClicked(evt);
            }
        });
        getContentPane().add(jButton10_Ville);
        jButton10_Ville.setBounds(440, 430, 72, 30);

        jButton11_Photo.setText("Photo");
        jButton11_Photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11_PhotoMousePressed(evt);
            }
        });
        getContentPane().add(jButton11_Photo);
        jButton11_Photo.setBounds(846, 230, 72, 30);

        jLabel14_Avatar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14_Avatar.setMaximumSize(new java.awt.Dimension(142, 167));
        jLabel14_Avatar.setMinimumSize(new java.awt.Dimension(142, 167));
        jLabel14_Avatar.setPreferredSize(new java.awt.Dimension(142, 167));
        getContentPane().add(jLabel14_Avatar);
        jLabel14_Avatar.setBounds(800, 50, 142, 167);

        jLabel13_CP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13_CP.setText("jLabel2");
        getContentPane().add(jLabel13_CP);
        jLabel13_CP.setBounds(820, 400, 37, 16);

        jLabel7_CodePostal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7_CodePostal.setText("Code Postal");
        getContentPane().add(jLabel7_CodePostal);
        jLabel7_CodePostal.setBounds(440, 390, 80, 16);

        jLabel6_Adresse.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_Adresse.setText("Adresse");
        getContentPane().add(jLabel6_Adresse);
        jLabel6_Adresse.setBounds(440, 310, 60, 16);

        jLabel8_Message.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8_Message.setText("                                                                                                                    Message");
        getContentPane().add(jLabel8_Message);
        jLabel8_Message.setBounds(140, 510, 800, 16);

        jLabel3_Phrase.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3_Phrase);
        jLabel3_Phrase.setBounds(500, 280, 420, 20);

        jLabel2_LittleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/technology-background-1632715.jpg"))); // NOI18N
        jLabel2_LittleBackground.setOpaque(true);
        getContentPane().add(jLabel2_LittleBackground);
        jLabel2_LittleBackground.setBounds(430, 50, 510, 460);

        jLabel9_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/background.jpg"))); // NOI18N
        getContentPane().add(jLabel9_Background);
        jLabel9_Background.setBounds(0, 0, 950, 570);
        getContentPane().add(jLabel11_Background);
        jLabel11_Background.setBounds(0, 0, 520, 0);
        getContentPane().add(jLabel12_Background);
        jLabel12_Background.setBounds(0, 270, 520, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // chargerLesUtilisateurs
    private void chargerLesUtilisateurs() {

        lesUtilisateurs.clear();
        lesUtilisateurs = dao.list();
        chargerTableauUtilisateurs();
    }

    private void chargerTableauUtilisateurs() {

        DefaultTableModel uiTable = (DefaultTableModel) jTable1.getModel();

        uiTable.setRowCount(0);

        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUtNom();
            row[1] = unUtilisateur.getUtPrenom();
            row[2] = unUtilisateur.getUtPseudo();

            uiTable.addRow(row);
        }
    }

    // methode pour changer d'utilisateur
    public void changeSelectUt() {
        // poiter sur la colonne selectionnée
        int i = jTable1.getSelectedRow();
        // récupérer les données de l'utilisateur
        // utiliser les données du tableau ou ...
        TableModel model = jTable1.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString());
        jTextField2_Nom.setText(unUtilisateur.getUtNom());
        jTextField1_Prenom.setText(unUtilisateur.getUtPrenom());
        jTextField3_Utilisateur.setText(unUtilisateur.getUtPseudo());
        jTextField4_Mail.setText(unUtilisateur.getUtMail());
        jTextField5_MotDePassse.setText(unUtilisateur.getUtMp());
        jLabel3_Phrase.setText(unUtilisateur.getUtPhrase());
        jTextField6_Adresse.setText(unUtilisateur.getUtAdr1());
        jTextField7_Adresse2.setText(unUtilisateur.getUtAdr2());
        jTextField8_CodePostal.setText(unUtilisateur.getUtCdpost());
        uiNumpost = unUtilisateur.getUtNumpost();
        jTextField9_Ville.setText(unUtilisateur.getUtCommune());
        commune.setNom_Commune(jTextField9_Ville.getText());
    }

    public void changeCommune() {
        jLabel13_CP.setVisible(true);
    }

    // methode pour afficher un message
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        jLabel8_Message.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8_Message.setText(msg);
    }

    // methode to show an error alert
    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        jLabel8_Message.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8_Message.setText(msg);
    }

    private void jTextField2_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_NomActionPerformed

    private void jTextField3_UtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_UtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_UtilisateurActionPerformed

    private void jButton1_CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CreerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_CreerActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton9_QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9_QuitterMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Mainform mainform = new Mainform();
        mainform.setVisible(true);
    }//GEN-LAST:event_jButton9_QuitterMouseClicked

    private void jButton1_CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_CreerMouseClicked
        // TODO add your handling code here:
        Utilisateur utilisateur = new Utilisateur(jTextField3_Utilisateur.getText(), jTextField2_Nom.getText(), jTextField1_Prenom.getText(), jTextField5_MotDePassse.getText(), jTextField4_Mail.getText(), jLabel3_Phrase.getText(), jTextField6_Adresse.getText(), jTextField7_Adresse2.getText(), jTextField8_CodePostal.getText(), "0", jTextField9_Ville.getText());
        dao.create(utilisateur);
        chargerLesUtilisateurs();
    }//GEN-LAST:event_jButton1_CreerMouseClicked

    private void jButton4_NouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_NouveauMouseClicked
        // TODO add your handling code here:
        jTextField2_Nom.setText("");
        jTextField1_Prenom.setText("");
        jTextField3_Utilisateur.setText("");
        jTextField4_Mail.setText("");
        jTextField5_MotDePassse.setText("");
        jLabel3_Phrase.setText("");
        jTextField6_Adresse.setText("");
        jTextField7_Adresse2.setText("");
        jTextField8_CodePostal.setText("");
        jTextField9_Ville.setText("");
    }//GEN-LAST:event_jButton4_NouveauMouseClicked

    private void jButton3_SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_SupprimerMouseClicked
        // TODO add your handling code here:
        String pseudo = jTextField3_Utilisateur.getText();
        dao.delete(pseudo);
        chargerLesUtilisateurs();
        jTextField2_Nom.setText("");
        jTextField1_Prenom.setText("");
        jTextField3_Utilisateur.setText("");
        jTextField4_Mail.setText("");
        jTextField5_MotDePassse.setText("");
        jLabel3_Phrase.setText("");
        jTextField6_Adresse.setText("");
        jTextField7_Adresse2.setText("");
        jTextField8_CodePostal.setText("");
        jTextField9_Ville.setText("");
    }//GEN-LAST:event_jButton3_SupprimerMouseClicked

    private void jButton2_ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_ModifierMouseClicked
        // TODO add your handling code here:
        Utilisateur utilisateur = new Utilisateur(jTextField3_Utilisateur.getText(), jTextField2_Nom.getText(), jTextField1_Prenom.getText(), jTextField5_MotDePassse.getText(), jTextField4_Mail.getText(), jLabel3_Phrase.getText(), jTextField6_Adresse.getText(), jTextField7_Adresse2.getText(), jTextField8_CodePostal.getText(), jLabel13_CP.getText(), jTextField9_Ville.getText());
        dao.update(utilisateur);
        chargerLesUtilisateurs();
    }//GEN-LAST:event_jButton2_ModifierMouseClicked

    private void jButton6_MailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_MailMouseClicked
        // TODO add your handling code here:
        Mail jfMail = new Mail();
        jfMail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6_MailMouseClicked

    private void jButton10_VilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10_VilleMouseClicked
        // TODO add your handling code here:
        SelectVille ville = new SelectVille(UtilCrud, true);
        ville.chargerCommunes(Integer.parseInt(jTextField8_CodePostal.getText()));
        ville.setVisible(true);
        jTextField9_Ville.setText(ville.getSelectedVille().getNom_Commune());
        jLabel13_CP.setText(ville.getSelectedVille().getNum_Postal());
    }//GEN-LAST:event_jButton10_VilleMouseClicked

    private void jButton11_PhotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11_PhotoMousePressed
        // TODO add your handling code here:
        SelectAvatar avatar = new SelectAvatar (UtilCrud, true);
        avatar.setVisible(true);
    }//GEN-LAST:event_jButton11_PhotoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10_Ville;
    private javax.swing.JButton jButton11_Photo;
    private javax.swing.JButton jButton1_Creer;
    private javax.swing.JButton jButton2_Modifier;
    private javax.swing.JButton jButton3_Supprimer;
    private javax.swing.JButton jButton4_Nouveau;
    private javax.swing.JButton jButton5_Parametre;
    private javax.swing.JButton jButton6_Mail;
    private javax.swing.JButton jButton7_AuSujet;
    private javax.swing.JButton jButton8_Aide;
    private javax.swing.JButton jButton9_Quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11_Background;
    private javax.swing.JLabel jLabel12_Background;
    private javax.swing.JLabel jLabel13_CP;
    private javax.swing.JLabel jLabel14_Avatar;
    private javax.swing.JLabel jLabel2_LittleBackground;
    private javax.swing.JLabel jLabel2_Nom;
    private javax.swing.JLabel jLabel3_Phrase;
    private javax.swing.JLabel jLabel3_Prenom;
    private javax.swing.JLabel jLabel4_Utilisateur;
    private javax.swing.JLabel jLabel5_Mail;
    private javax.swing.JLabel jLabel6_Adresse;
    private javax.swing.JLabel jLabel6_MotDePasse;
    private javax.swing.JLabel jLabel7_CodePostal;
    private javax.swing.JLabel jLabel8_Message;
    private javax.swing.JLabel jLabel9_Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_Prenom;
    private javax.swing.JTextField jTextField2_Nom;
    private javax.swing.JTextField jTextField3_Utilisateur;
    private javax.swing.JTextField jTextField4_Mail;
    private javax.swing.JTextField jTextField5_MotDePassse;
    private javax.swing.JTextField jTextField6_Adresse;
    private javax.swing.JTextField jTextField7_Adresse2;
    private javax.swing.JTextField jTextField8_CodePostal;
    private javax.swing.JTextField jTextField9_Ville;
    // End of variables declaration//GEN-END:variables
}
